---
# file: bind/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- include: installation.yml
  tags: installation
  become: yes

- include: configuration.yml
  tags: configuration
  become: yes

- include: apparmor.yml
  tags: apparmor
  become: yes
